name: Send Stock Price Only

on:
  schedule:
    # 💡 여기에 원하는 시간을 설정하세요 (현재 설정은 한국 시간 낮 12시 30분, 오후 3시 40분)
    # 한국 시간에서 9시간을 뺀 UTC 시간으로 적어야 합니다.
    - cron: '30 3,6 * * 1-5' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install telethon requests

      - name: Run price script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}
          KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
          KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
        # 💡 1단계에서 만든 price.py를 실행하라는 명령입니다.
        run: python price.py
